#!/bin/bash

echo "🚀 Collectiva Deployment Helper"
echo "==============================="
echo ""

# Check if git remote exists
if git remote get-url origin > /dev/null 2>&1; then
    echo "✅ Git remote already configured"
    echo "Current remote: $(git remote get-url origin)"
    echo ""
    echo "⚠️  IMPORTANT: Check if your repository is PUBLIC"
    echo "   Vercel free tier requires public repositories!"
    echo ""
    echo "To make your repository public:"
    echo "1. Go to: $(git remote get-url origin)"
    echo "2. Click Settings → Scroll down to 'Danger Zone'"
    echo "3. Click 'Change repository visibility' → 'Make public'"
    echo "4. Type repository name to confirm"
else
    echo "⚠️  No Git remote found"
    echo ""
    echo "Please follow these steps:"
    echo "1. Create a new repository on GitHub.com"
    echo "2. Repository name: collectiva"
    echo "3. ⚠️  IMPORTANT: Make it PUBLIC (required for Vercel free tier)"
    echo "4. Then run:"
    echo ""
    echo "   git remote add origin https://github.com/YOUR_USERNAME/collectiva.git"
    echo "   git push -u origin main"
    echo ""
fi

echo ""
echo "📋 Deployment Checklist:"
echo "========================"
echo ""
echo "✅ GitHub repository created"
echo "✅ Code pushed to GitHub"
echo "✅ Vercel account created"
echo "✅ Repository imported to Vercel"
echo "✅ First deployment completed"
echo ""
echo "🎯 Next Development Phase:"
echo "========================="
echo "✅ Database setup (PostgreSQL)"
echo "✅ Authentication system (NextAuth.js)"
echo "✅ Real user registration"
echo "🔄 Database deployment (Vercel Postgres) - IN PROGRESS"
echo "□ Organization management"
echo "□ Payment integration (Stripe)"
echo "□ AI fund distribution"
echo ""
echo "🚀 IMMEDIATE NEXT STEP:"
echo "1. Go to Vercel Dashboard → Storage → Create Postgres DB"
echo "2. Run: npm run db:deploy"
echo "3. Test registration at: collectiva-nevi9999.vercel.app/sign-up"
echo ""
echo "🌐 After deployment, your app will be available at:"
echo "   https://collectiva-nevi9999.vercel.app"
echo ""
echo "📝 Vercel Free Tier Limits:"
echo "   ✅ 100GB bandwidth/month"
echo "   ✅ 10 second function timeout"
echo "   ✅ Single region deployment (automatic)"
echo "   ⚠️  Multi-region requires Pro plan ($20/month)"
echo ""
echo "📖 For detailed instructions, see: DEPLOYMENT.md"
echo ""

# Check if build works
echo "🔧 Testing production build..."
if npm run build > /dev/null 2>&1; then
    echo "✅ Build successful - ready for deployment!"
else
    echo "❌ Build failed - please fix errors before deploying"
fi

echo ""
echo "🎯 Quick Start:"
echo "1. Push to GitHub: git push origin main"
echo "2. Import to Vercel: vercel.com/new"
echo "3. Your app goes live automatically!"
